# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: build
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci && npm run build

# Stage 2: production
FROM node:lts-alpine
WORKDIR /app
# Copy built files and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
RUN npm ci --omit=dev && chmod +x build/index.js

# Use shell entrypoint to generate config and start server
ENTRYPOINT ["sh"]
CMD []
